### ISSUE TITLE
/home/wallets/Downloads/Bitbucket/cloner/cloner.sh: 38: mr: not found

### ISSUE THREAD

**Issue by europound** [mimo84/cloner#2]
/home/wallets/Downloads/Bitbucket/cloner/cloner.sh: 38: mr: not found
Cloning into 'deploy'...
git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/home/wallets/Downloads/Bitbucket/cloner/cloner.sh: 38: mr: not found

**Comment by mimo84** [comment]
`mr` is a git packages manager that allows you to update several repositories at once, since I use it for my own projects, I register each one with it. 
You can find more info about it here: [https://myrepos.branchable.com/](https://myrepos.branchable.com/)
